- name: lotus-setup
  hosts: lotus_full_node
  roles:
    - role: geerlingguy.go 
      go_version: "1.20.7"
      go_platform: linux
      go_arch: amd64
      go_checksum: 'f0a87f1bcae91c4b69f8dc2bc6d7e6bfcd7524fceec130af525058c0c17b1b44'
  become: true
  remote_user: ubuntu
  gather_facts: false
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_profile: default
    ansible_aws_ssm_bucket_name: lotus-aws-ssm-connection-playbook
    ansible_aws_ssm_region: "us-east-1"
  tasks:
    - name: pinging
      ping:

    - name: create dir for code
      file:
        path: /home/lotus
        state: directory

    - name: Install Lotus Dependancies for Ubuntu
      shell: |
        sudo apt install mesa-opencl-icd ocl-icd-opencl-dev gcc git bzr jq pkg-config curl clang build-essential hwloc libhwloc-dev wget -y && sudo apt upgrade -y
      register: result_lotus_dependancies

    - name: check if cargo is installed
      shell: command -v cargo
      register: cargo_exists
      ignore_errors: yes

    - name: Download Installer
      when: cargo_exists is failed
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: '0755'
        force: 'yes'
      tags:
        - rust

    - name: install rust/cargo
      when: cargo_exists is failed
      shell: /tmp/sh.rustup.rs -y
      tags:
        - rust

    - name: Clone Lotus
      shell: |
        cd ../../../../home/
        git clone https://github.com/filecoin-project/lotus.git
      register: result_clone_lotus

    - name: Checkout Releases for Lotus
      shell: |
        cd ../../../../home/lotus
        git checkout releases
      register: result_checkout_lotus
 
    - name: Join Mainnet [Enable the use of SHA extensions]
      shell: |
        cd ../../../../home/lotus
        export PATH=$PATH:/usr/local/go/bin
        export CGO_CFLAGS_ALLOW="-D__BLST_PORTABLE__"
        export CGO_CFLAGS="-D__BLST_PORTABLE__"
        make clean all
        export PATH=$PATH:/usr/local/go/bin
        sudo make install
      register: result_mainnet_lotus

    - name: Check Version
      shell: |
        cd ../../../../home/lotus
        lotus --version
      register: result_version_lotus

    # - name: "Update Lotus config.toml"
    #   copy:
    #       src: config.toml
    #       dest: ~/.lotus/config.toml

    # - name: Start the node
    #   shell: |
    #     cd ../../../../home/lotus
    #     export PATH=$PATH:/usr/local/go/bin
    #     nohup lotus daemon > lotus.log &
    #   register: result_start_lotus
