- name: lotus-setup
  hosts: lotus_full_node
  become: true
  remote_user: ubuntu
  gather_facts: false
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_profile: default
    ansible_aws_ssm_bucket_name: lotus-aws-ssm-connection-playbook
    ansible_aws_ssm_region: "us-east-1"
  tasks:
    - name: pinging
      ping:
